name: deploy root layer
run-name: deploy root layer - ${{ github.event.inputs.terraform_action }}

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        default: plan
        description: terraform action
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice

permissions:
  contents: read
  id-token: write

jobs:
  deploy_root_layer:
    name: "deploy root layer - ${{ github.event.inputs.terraform_action }}"
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      terraform_action: ${{ github.event.inputs.terraform_action }}
      terraform_layer: root_layer
    secrets: inherit
