name: deploy init
run-name: deploy init - ${{ github.event.inputs.terraform_action }}

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'select terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    uses: ./.github/workflows/reusable_terraform_action.yaml
    with:
      terraform_action: plan
    secrets: inherit

  get-approval:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.terraform_action == 'apply' }}
    environment: approval_required
    needs: plan
    steps:
      - name: Approval requested
        run: echo 'Approval provided.  Job will continue.'

  apply:
    if: ${{ github.event.inputs.terraform_action == 'apply' }}
    needs: get-approval
    uses: ./.github/workflows/reusable_terraform_action.yaml
    with:
      terraform_action: apply
    secrets: inherit
