name: deploy_tf_root_layer
run-name: deploy tf on root layer - ${{ github.event.inputs.terraform_action }}

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - plan destroy
          - apply
          - destroy
      import:
        description: 'import'
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    uses: ./.github/workflows/reusable_terraform_action.yaml
    if: ${{ github.event.inputs.terraform_action == 'plan' || github.event.inputs.terraform_action == 'apply' }}
    with:
      import: ${{ github.event.inputs.import }}
      terraform_action: plan
      working_directory: './root'
    secrets: inherit

  plan-destroy:
    uses: ./.github/workflows/reusable_terraform_action.yaml
    if: ${{ github.event.inputs.terraform_action == 'plan destroy' || github.event.inputs.terraform_action == 'destroy' }}
    with:
      import: ${{ github.event.inputs.import }}
      terraform_action: plan destroy
      working_directory: './root'
    secrets: inherit

  get-approval-for-apply:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.terraform_action == 'apply' }}
    environment: approval_required
    needs: plan
    steps:
      - name: Approval requested
        run: echo 'Approval provided.  Job will continue.'

  get-approval-for-destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.terraform_action == 'destroy' }}
    environment: approval_required
    needs: plan-destroy
    steps:
      - name: Approval requested
        run: echo 'Approval provided.  Job will continue.'