name: linter
run-name: "linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # terraform-fmt checks the formatting of Terraform configuration files.
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false
      - run: terraform --version
      - run: terraform fmt -check -diff -recursive .

  # trivy is a security scanner for container images, file systems, and Git repositories.
  # It detects vulnerabilities, misconfigurations, and other security issues in the scanned targets,
  # helping to ensure that the code and configurations are secure and compliant with best practices.
  # This job specifically checks the configuration files for security issues.
  trivy-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquasecurity/setup-trivy@9ea583eb67910444b1f64abf338bd2e105a0a93d # v0.2.3
      - run: trivy --version
      - run: trivy config --exit-code 1 .

  # actionlint is a linter for GitHub Actions workflows. It checks for syntax errors, best practices,
  # and potential issues in workflow files, helping to ensure that workflows are correctly defined
  # and follow best practices.
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker://rhysd/actionlint:1.7.7
        with:
          args: -color

  # tflint is a Terraform linter that checks for best practices and potential issues in Terraform
  # configurations. It helps ensure that Terraform code adheres to best practices and is free from
  # common pitfalls, improving the quality and maintainability of infrastructure as code.
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1
      - run: tflint --version
      - run: tflint --recursive

  # shellcheck is a tool for analyzing shell scripts to detect syntax errors, stylistic issues,
  # and potential bugs. It helps ensure that shell scripts follow best practices and are
  # free from common pitfalls.
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
        with:
          scandir: ./scripts
