name: reusable tf action
run-name: reusable tf action on ${{ inputs.working_directory }} - ${{ inputs.terraform_action }}

on: 
  workflow_call:
    inputs:
      terraform_action:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      import:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - plan destroy
          - apply
          - destroy
      working_directory:
        description: 'working directory'
        required: true
        default: './init'
        type: choice
        options:
          - ./init
      import:
        description: 'import'
        required: false
        default: true
        type: boolean

env:
  TF_LOG: OFF
  TF_LOG_CORE: OFF
  TF_LOG_PROVIDER: OFF
  TF_LOG_PATH: ./terraform.log
  TF_VAR_import: ${{ inputs.import }}

permissions:
  contents: read
  id-token: write

jobs:
  terraform_action:
    name: "tf action on ${{ inputs.working_directory }} - ${{ inputs.terraform_action }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false
      - run: terraform --version
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # 4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
          aws-region: us-east-2
      - name: dump context
        run: |
          echo -e "Dumping context...\n"
          echo -e "env context:\n${{ toJson(env) }}\n"
          echo -e "github context:\n${{ toJson(github) }}\n"
      - run: terraform init
      - run: terraform validate
      - run: terraform plan
        if: ${{ inputs.terraform_action == 'plan' }}
      - run: terraform plan -destroy
        if: ${{ inputs.terraform_action == 'plan destroy' }}
      - run: terraform apply -auto-approve
        if: ${{ inputs.terraform_action == 'apply' }}
      - run: terraform apply -destroy -auto-approve
        if: ${{ inputs.terraform_action == 'destroy' }}
