name: reusable deploy
run-name: deploy ${{ inputs.terraform_layer }} - ${{ inputs.terraform_action }}

on:
  workflow_call:
    inputs:
      terraform_action:
        required: true
        type: string
      terraform_layer:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      terraform_action:
        default: plan
        description: terraform action
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice
      terraform_layer:
        default: admin_layer
        description: terraform layer
        options:
          - admin_layer
          - root_layer
        required: true
        type: choice

permissions:
  contents: read
  id-token: write

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: pwd

  plan:
    name: plan ${{ inputs.terraform_layer }}
    uses: ./.github/workflows/reusable_terraform_action.yaml
    if: ${{ inputs.terraform_action == 'plan' || inputs.terraform_action == 'apply' }}
    needs: start
    with:
      terraform_action: plan
      terraform_layer: ${{ inputs.terraform_layer }}
    secrets: inherit

  plan_destroy:
    name: plan destroy ${{ inputs.terraform_layer }}
    uses: ./.github/workflows/reusable_terraform_action.yaml
    if: ${{ inputs.terraform_action == 'plan destroy' || inputs.terraform_action == 'destroy' }}
    needs: start
    with:
      terraform_action: plan destroy
      terraform_layer: ${{ inputs.terraform_layer }}
    secrets: inherit

  get_approval_for_apply:
    name: get approval for apply on ${{ inputs.terraform_layer }}
    runs-on: ubuntu-latest
    if: ${{ inputs.terraform_action == 'apply' }}
    environment: approval_required
    needs: plan
    steps:
      - name: Approval requested
        run: echo 'Approval provided.  Job will continue.'

  get_approval_for_destroy:
    name: get approval for destroy on ${{ inputs.terraform_layer }}
    runs-on: ubuntu-latest
    if: ${{ inputs.terraform_action == 'destroy' }}
    environment: approval_required
    needs: plan_destroy
    steps:
      - name: Approval requested
        run: echo 'Approval provided.  Job will continue.'

  apply:
    name: apply ${{ inputs.terraform_layer }}
    uses: ./.github/workflows/reusable_terraform_action.yaml
    if: ${{ inputs.terraform_action == 'apply' }}
    needs: get_approval_for_apply
    with:
      terraform_action: apply
      terraform_layer: ${{ inputs.terraform_layer }}
    secrets: inherit

  destroy:
    name: destroy ${{ inputs.terraform_layer }}
    uses: ./.github/workflows/reusable_terraform_action.yaml
    if: ${{ inputs.terraform_action == 'destroy' }}
    needs: get_approval_for_destroy
    with:
      terraform_action: destroy
      terraform_layer: ${{ inputs.terraform_layer }}
    secrets: inherit
